version: "3.9"
services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
    - ./init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    - stl-volume:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
    - stl-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    volumes:
      - stl-volume:/data
    networks:
    - stl-network

  stl-backend:
    image: stl-backend
    restart: always
    ports:
      - 8080:8080
    environment:
      PORT_STL_BACKEND: 8080
      MONGODB_URI: 'mongodb://stluser:stluser@mongo:27017/stl?directConnection\=true&serverSelectionTimeoutMS\=2000&appName\=mongosh+1.3.1'
    depends_on:
      - mongo
    networks:
      - stl-network
    volumes:
      - stl-volume:/data

networks:
  stl-network:
    driver: bridge

volumes:
  stl-volume: